FROM maven:3.9.3-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .

RUN mvn clean install -DskipTests
FROM openjdk:21-jdk-slim
WORKDIR /app
COPY --from=build /app/target/*.jar  app.jar
EXPOSE 8083
CMD ["java", "-jar", "/app/bff-app.jar"]
